import { Platform, StyleSheet } from "react-native";
import type { AppTheme } from "./types";
import { themes } from "./theme";

export const createStyles = (themeName: AppTheme) => {
  const theme = themes[themeName];

  return StyleSheet.create({
  loadingScreen: {
    flex: 1,
    backgroundColor: theme.background,
    alignItems: "center",
    justifyContent: "center",
  },
  loadingText: {
    color: "#395441",
    fontSize: 15,
    fontWeight: "800",
    marginTop: 14,
  },
  authScreen: {
    flex: 1,
    backgroundColor: theme.background,
    justifyContent: "center",
    paddingHorizontal: 22,
  },
  authCard: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 22,
  },
  authEyebrow: {
    color: "#395441",
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 2,
    marginBottom: 9,
  },
  authTitle: {
    color: "#101411",
    fontSize: 34,
    fontWeight: "900",
    marginBottom: 10,
  },
  authDescription: {
    color: "#687069",
    fontSize: 15,
    lineHeight: 21,
    marginBottom: 24,
  },
  authLabel: {
    color: theme.text,
    fontSize: 14,
    fontWeight: "800",
    marginBottom: 7,
  },
  authInput: {
    backgroundColor: "#F1F4F0",
    borderRadius: 14,
    paddingHorizontal: 15,
    paddingVertical: 14,
    color: "#151A16",
    fontSize: 16,
    marginBottom: 16,
  },
  authPrimaryButton: {
    backgroundColor: theme.primary,
    borderRadius: 14,
    minHeight: 52,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  authButtonDisabled: {
    opacity: 0.65,
  },
  authPrimaryButtonText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  authSwitchButton: {
    alignItems: "center",
    paddingVertical: 17,
  },
  authSwitchText: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: "800",
  },
  topRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  titleArea: {
    flex: 1,
    paddingRight: 12,
  },
  syncText: {
    color: "#54715D",
    fontSize: 12,
    fontWeight: "800",
    marginTop: -14,
    marginBottom: 18,
  },
  syncTextError: {
    color: "#A23D32",
  },
  logoutButton: {
    backgroundColor: theme.soft,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 10,
    marginTop: 2,
  },
  logoutButtonText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
  },
  container: { flex: 1, backgroundColor: "#070B14",
  },
  premiumPressed: {
    opacity: 0.78,
    transform: [{ scale: 0.97 }],
  },
  bottomNav: { flexDirection: "row", backgroundColor: "#0D131F", borderTopWidth: 1, borderTopColor: "#242D40", paddingTop: 8, paddingBottom: Platform.OS === "ios" ? 18 : 10, paddingHorizontal: 10,
  },
  navButton: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: 56, borderRadius: 18, overflow: "hidden",
  },
  navButtonActive: { backgroundColor: "#1B2032", borderWidth: 1, borderColor: "#332B56",
  },
  navButtonText: { color: "#7F8AA0", fontSize: 11, fontWeight: "700",
  },
  navButtonTextActive: { color: "#9B87FF",
  },
  numericDoneButton: {
    alignSelf: "flex-end",
    backgroundColor: theme.primary,
    borderRadius: 11,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 18,
  },
  numericDoneButtonText: {
    color: theme.card,
    fontSize: 14,
    fontWeight: "900",
  },
  quickAddScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  quickAddHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  quickAddTitle: {
    color: theme.text,
    fontSize: 26,
    fontWeight: "900",
  },
  quickAddClose: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  quickAddContent: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  quickAddName: {
    color: theme.text,
    fontSize: 23,
    fontWeight: "900",
    marginBottom: 24,
  },
  quickAddLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 8,
  },
  quickAddInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 18,
    marginBottom: 12,
  },
  quickAmountRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 20,
  },
  quickAmountButton: {
    flex: 1,
    backgroundColor: theme.soft,
    borderRadius: 11,
    paddingVertical: 11,
    alignItems: "center",
  },
  quickAmountButtonText: {
    color: theme.primary,
    fontWeight: "800",
  },
  quickPreviewCard: {
    backgroundColor: theme.card,
    borderRadius: 14,
    padding: 15,
    marginTop: 4,
    marginBottom: 16,
  },
  quickPreviewTitle: {
    color: "#687069",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
  },
  quickPreviewText: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 3,
  },
  quickAddConfirmButton: {
    backgroundColor: theme.primary,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
  },
  quickAddConfirmText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  editScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  editHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  editTitle: {
    color: theme.text,
    fontSize: 26,
    fontWeight: "900",
  },
  editCloseText: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  editContent: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  editFoodName: {
    color: theme.text,
    fontSize: 22,
    fontWeight: "900",
    marginBottom: 24,
  },
  editLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 8,
  },
  editInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    marginBottom: 18,
  },
  editSaveButton: {
    backgroundColor: theme.primary,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
    marginTop: 8,
  },
  editSaveButtonText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  editDeleteButton: {
    borderWidth: 1,
    borderColor: "#B64A3B",
    borderRadius: 15,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 12,
  },
  editDeleteButtonText: {
    color: "#A23D32",
    fontSize: 15,
    fontWeight: "900",
  },
  targetProgressTrack: {
    height: 8,
    backgroundColor: theme.soft,
    borderRadius: 999,
    overflow: "hidden",
    marginTop: 10,
  },
  targetProgressFill: {
    height: "100%",
    backgroundColor: theme.primary,
    borderRadius: 999,
  },
  targetSaveButton: {
    backgroundColor: theme.soft,
    borderRadius: 15,
    paddingVertical: 15,
    alignItems: "center",
    marginBottom: 12,
  },
  targetSaveButtonText: {
    color: theme.primary,
    fontSize: 15,
    fontWeight: "900",
  },
  weightTargetSummary: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 6,
  },
  macroGoalCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
  },
  macroGoalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  macroGoalTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "900",
  },
  macroGoalEdit: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: "900",
  },
  macroProgressItem: {
    marginBottom: 13,
  },
  macroProgressHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  macroProgressLabel: {
    color: theme.text,
    fontSize: 14,
    fontWeight: "800",
  },
  macroProgressValue: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  macroProgressTrack: {
    height: 9,
    backgroundColor: theme.soft,
    borderRadius: 999,
    overflow: "hidden",
  },
  macroProgressFill: {
    height: "100%",
    backgroundColor: theme.primary,
    borderRadius: 999,
  },
  weightCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  weightCardText: {
    flex: 1,
    paddingRight: 12,
  },
  weightCardTitle: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 5,
  },
  weightCardValue: {
    color: theme.primary,
    fontSize: 20,
    fontWeight: "900",
  },
  weightCardChange: {
    color: "#687069",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 4,
  },
  weightButton: {
    backgroundColor: theme.primary,
    borderRadius: 12,
    paddingHorizontal: 15,
    paddingVertical: 11,
  },
  weightButtonText: {
    color: theme.card,
    fontWeight: "900",
  },
  weightScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  weightHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  weightTitle: {
    color: theme.text,
    fontSize: 26,
    fontWeight: "900",
  },
  weightCloseText: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  weightContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
  },
  weightDateCard: {
    backgroundColor: theme.card,
    borderRadius: 14,
    padding: 14,
    marginBottom: 18,
  },
  weightDateLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 4,
  },
  weightDateValue: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  weightLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 8,
  },
  weightInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 20,
    marginBottom: 12,
  },
  weightSaveButton: {
    backgroundColor: theme.primary,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
  },
  weightSaveButtonText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  weightNote: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 12,
  },
  weightGraph: {
    minHeight: 190,
    flexDirection: "row",
    alignItems: "flex-end",
    gap: 8,
    paddingTop: 8,
  },
  weightGraphColumn: {
    flex: 1,
    minWidth: 24,
    alignItems: "center",
  },
  weightGraphValue: {
    color: theme.primary,
    fontSize: 10,
    fontWeight: "900",
    marginBottom: 5,
  },
  weightGraphTrack: {
    height: 140,
    width: "100%",
    justifyContent: "flex-end",
    alignItems: "center",
    backgroundColor: theme.soft,
    borderRadius: 10,
    overflow: "hidden",
  },
  weightGraphBar: {
    width: "68%",
    backgroundColor: theme.primary,
    borderRadius: 8,
  },
  weightGraphDate: {
    color: theme.textMuted,
    fontSize: 9,
    fontWeight: "700",
    marginTop: 6,
  },
  weightGraphSummary: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: "800",
    textAlign: "center",
    marginTop: 14,
  },
  weightHistoryCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
  },
  weightHistoryRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingVertical: 12,
  },
  weightHistoryDate: {
    color: theme.textMuted,
    fontSize: 14,
    fontWeight: "700",
    textTransform: "capitalize",
  },
  weightHistoryValue: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "900",
  },
  profileCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  profileCardText: {
    flex: 1,
    paddingRight: 12,
  },
  profileCardTitle: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "900",
    marginBottom: 5,
  },
  profileCardDescription: {
    color: "#687069",
    fontSize: 13,
    lineHeight: 18,
  },
  profileButton: {
    backgroundColor: theme.primary,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  profileButtonText: {
    color: theme.card,
    fontWeight: "900",
  },
  profileScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  profileHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  profileTitle: {
    color: theme.text,
    fontSize: 26,
    fontWeight: "900",
  },
  profileCloseText: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  profileContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  profileLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 8,
  },
  profileInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    marginBottom: 16,
  },
  optionRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  optionRowWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 20,
  },
  optionColumn: {
    gap: 9,
    marginBottom: 18,
  },
  optionButton: {
    backgroundColor: theme.soft,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 11,
  },
  optionButtonWide: {
    backgroundColor: theme.soft,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  optionButtonSelected: {
    backgroundColor: theme.primary,
  },
  optionButtonText: {
    color: theme.primary,
    fontWeight: "800",
  },
  optionButtonTextSelected: {
    color: theme.card,
  },
  calculateButton: {
    backgroundColor: theme.primaryDark,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
  },
  calculateButtonText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  calculatorNote: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 12,
    textAlign: "center",
  },
  accountCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginTop: 4,
    marginBottom: 18,
  },
  accountTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "900",
    marginBottom: 7,
  },
  accountDescription: {
    color: "#687069",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 14,
  },
  deleteAccountButton: {
    borderWidth: 1,
    borderColor: "#B64A3B",
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: "center",
  },
  deleteAccountButtonText: {
    color: "#A23D32",
    fontSize: 15,
    fontWeight: "900",
  },
  historyTabs: { flexDirection: "row", backgroundColor: "#111722", borderRadius: 16, padding: 4, marginBottom: 14, borderWidth: 1, borderColor: "#273044",
  },
  historyTabButton: { flex: 1, alignItems: "center", borderRadius: 12, paddingVertical: 11,
  },
  historyTabButtonActive: { backgroundColor: "#7458F5",
  },
  historyTabText: { color: "#8995AA", fontSize: 12, fontWeight: "800",
  },
  historyTabTextActive: { color: "#FFFFFF",
  },
  historyCard: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 15, marginBottom: 12,
  },
  historyText: { color: "#DCE2EE", fontSize: 13, lineHeight: 20,
  },

  content: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 28,
  },
  eyebrow: {
    color: "#395441",
    fontSize: 15,
    fontWeight: "800",
    letterSpacing: 2,
    marginBottom: 8,
  },
  title: {
    color: "#101411",
    fontSize: 38,
    fontWeight: "900",
    marginBottom: 24,
  },
  dateCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 10,
    marginBottom: 16,
    flexDirection: "row",
    alignItems: "center",
  },
  dateArrow: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  dateArrowText: {
    color: theme.primary,
    fontSize: 34,
    fontWeight: "700",
  },
  dateCenter: {
    flex: 1,
    alignItems: "center",
  },
  dateText: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  todayText: {
    color: "#3E714F",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 4,
  },
  copyPreviousDayButton: {
    backgroundColor: theme.soft,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 14,
    marginBottom: 14,
    flexDirection: "row",
    alignItems: "center",
  },
  copyPreviousDayText: {
    flex: 1,
    paddingRight: 12,
  },
  copyPreviousDayTitle: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "900",
    marginBottom: 3,
  },
  copyPreviousDayDescription: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  copyPreviousDayArrow: {
    color: theme.primary,
    fontSize: 29,
    fontWeight: "700",
  },
  goalCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 18,
    marginBottom: 16,
  },
  goalTitle: {
    fontSize: 17,
    fontWeight: "800",
    marginBottom: 12,
  },
  goalRow: {
    flexDirection: "row",
    gap: 10,
  },
  goalInput: {
    flex: 1,
    backgroundColor: "#F1F4F0",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 17,
  },
  saveButton: {
    backgroundColor: theme.primary,
    borderRadius: 12,
    paddingHorizontal: 20,
    justifyContent: "center",
  },
  saveButtonText: {
    color: theme.card,
    fontWeight: "800",
  },
  summaryCard: {
    backgroundColor: theme.primaryDark,
    borderRadius: 24,
    flexDirection: "row",
    paddingVertical: 24,
    paddingHorizontal: 14,
    marginBottom: 12,
  },
  summaryColumn: {
    flex: 1,
    alignItems: "center",
  },
  summaryLabel: {
    color: "#B8C6BC",
    fontSize: 15,
    fontWeight: "700",
    marginBottom: 8,
  },
  summaryValue: {
    color: theme.card,
    fontSize: 19,
    fontWeight: "900",
  },
  separator: {
    width: 1,
    backgroundColor: "#315141",
    marginVertical: 4,
  },
  macroCard: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 28,
    gap: 6,
  },
  macroText: {
    color: "#395441",
    fontWeight: "800",
  },
  weekCard: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 15, marginBottom: 12,
  },
  weekTitle: { color: "#F7F9FD", fontSize: 17, fontWeight: "900",
  },
  weekSummaryRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 18,
  },
  weekSummaryItem: {
    flex: 1,
    backgroundColor: "#F1F4F0",
    borderRadius: 14,
    padding: 14,
  },
  weekSummaryLabel: { color: "#AEB8CC", fontSize: 12,
  },
  weekSummaryValue: { color: "#F7F8FC", fontSize: 22, fontWeight: "900", marginTop: 6,
  },
  weekDayRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 11,
  },
  weekDayLabel: { color: "#AAB4C6", fontSize: 11, width: 34,
  },
  weekBarTrack: { flex: 1, height: 9, backgroundColor: "#273044", borderRadius: 8, overflow: "hidden",
  },
  weekBarFill: { height: "100%", backgroundColor: "#7458F5", borderRadius: 8,
  },
  weekDayCalories: { color: "#DDE3EF", fontSize: 10, width: 62, textAlign: "right",
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitle: { color: "#F7F9FD", fontSize: 24, fontWeight: "900", marginBottom: 14,
  },
  clearText: {
    color: "#A23D32",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 14,
  },
  emptyDiary: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 18,
    marginBottom: 10,
  },
  emptyDiaryText: {
    color: "#687069",
    fontSize: 15,
  },
  mealSection: {
    marginBottom: 18,
  },
  mealSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  mealSectionTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "900",
  },
  mealSectionCalories: {
    color: "#395441",
    fontSize: 14,
    fontWeight: "800",
  },
  emptyMealText: {
    color: "#7A817B",
    backgroundColor: theme.card,
    borderRadius: 14,
    padding: 14,
  },
  diaryItem: {
    backgroundColor: theme.card,
    borderRadius: 16,
    padding: 17,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  removeHint: {
    color: "#7A817B",
    fontSize: 13,
    marginTop: 2,
    marginBottom: 30,
  },
  addHeroCard: {
    backgroundColor: "#111722",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#2A3347",
    padding: 17,
    marginBottom: 14,
  },
  addHeroTop: { flexDirection: "row", alignItems: "center", marginBottom: 15 },
  addHeroIcon: { width: 46, height: 46, borderRadius: 16, backgroundColor: "#7458F5", alignItems: "center", justifyContent: "center", marginRight: 12, shadowColor: "#7458F5", shadowOpacity: 0.4, shadowRadius: 10, elevation: 5 },
  addHeroIconText: { color: "#FFFFFF", fontSize: 27, fontWeight: "400", marginTop: -2 },
  addHeroText: { flex: 1 },
  addHeroTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  addHeroSubtitle: { color: "#8F9AAF", fontSize: 12, marginTop: 4 },
  addHeroSearch: { backgroundColor: "#0A0F19", color: "#FFFFFF", borderWidth: 1, borderColor: "#2C3650", borderRadius: 17, paddingHorizontal: 16, paddingVertical: 15, fontSize: 15 },
  addActionGrid: { flexDirection: "row", gap: 9, marginBottom: 22 },
  addActionCard: { flex: 1, minHeight: 120, backgroundColor: "#111722", borderWidth: 1, borderColor: "#273044", borderRadius: 20, padding: 13, justifyContent: "flex-end" },
  addActionPrimary: { backgroundColor: "#201A3A", borderColor: "#5C48C9" },
  addActionIcon: { color: "#A995FF", fontSize: 24, fontWeight: "900", marginBottom: 14 },
  addActionTitle: { color: "#FFFFFF", fontSize: 13, fontWeight: "900" },
  addActionText: { color: "#8792A7", fontSize: 10, marginTop: 4 },
  addSectionHeadingRow: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 10 },
  addSectionEyebrow: { color: "#806CF7", fontSize: 10, fontWeight: "900", letterSpacing: 1.5, marginBottom: 4 },
  addSectionHeading: { color: "#F7F9FD", fontSize: 18, fontWeight: "900" },
  addContentSection: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 15, marginBottom: 12 },
  addResultsHeader: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", marginTop: 8 },
  addResultCount: { color: "#A995FF", fontSize: 12, fontWeight: "900", marginBottom: 2 },

  mealLabel: { color: "#B8C2D4", fontSize: 13, fontWeight: "800", marginBottom: 9,
  },
  mealRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 18,
  },
  mealButton: { flexGrow: 1, minWidth: "46%", alignItems: "center", backgroundColor: "#111722", borderWidth: 1, borderColor: "#273044", borderRadius: 16, paddingHorizontal: 13, paddingVertical: 13,
  },
  mealButtonSelected: { backgroundColor: "#7458F5", borderColor: "#9B87FF", shadowColor: "#7458F5", shadowOpacity: 0.35, shadowRadius: 8, elevation: 4,
  },
  mealButtonText: { color: "#AEB8CA", fontSize: 12, fontWeight: "800",
  },
  mealButtonTextSelected: { color: "#FFFFFF",
  },
  manualButton: { backgroundColor: "#111722", borderWidth: 1, borderColor: "#273044", borderRadius: 18, paddingVertical: 15, alignItems: "center", marginTop: 10,
  },
  manualButtonText: { color: "#D9E0ED", fontSize: 14, fontWeight: "900",
  },
  manualContainer: {
    flex: 1,
    backgroundColor: theme.background,
  },
  manualHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  manualTitle: {
    color: theme.text,
    fontSize: 24,
    fontWeight: "900",
  },
  manualCloseText: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  manualContent: {
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  manualLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 8,
  },
  manualInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    marginBottom: 16,
  },
  manualMealText: {
    color: "#395441",
    fontWeight: "800",
    marginBottom: 18,
  },
  manualSaveButton: {
    backgroundColor: theme.primary,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
  },
  manualSaveButtonText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  templateMealRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 18,
  },
  templateMealButton: {
    backgroundColor: theme.soft,
    borderRadius: 11,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  templateMealButtonActive: {
    backgroundColor: theme.primary,
  },
  templateMealText: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  templateMealTextActive: {
    color: theme.card,
  },
  recipeSection: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 14, marginBottom: 12,
  },
  recipeHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  newRecipeButton: { backgroundColor: "#201A3A", borderRadius: 12, paddingHorizontal: 11, paddingVertical: 8,
  },
  newRecipeButtonText: { color: "#A995FF", fontSize: 11, fontWeight: "900",
  },
  recipeEmptyText: { color: "#8792A7", fontSize: 13, marginTop: 10,
  },
  recipeRow: { flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: "#252E40", paddingVertical: 12,
  },
  recipeCardV2: { backgroundColor: "#151C29", borderRadius: 18, borderWidth: 1, borderColor: "#293348", marginTop: 12, overflow: "hidden" },
  recipeCardMainV2: { padding: 14 },
  recipeCardTopV2: { flexDirection: "row", alignItems: "center" },
  recipeIconV2: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#24203D", alignItems: "center", justifyContent: "center", marginRight: 11 },
  recipeIconTextV2: { fontSize: 21 },
  recipeCaloriesBadgeV2: { minWidth: 58, borderRadius: 13, backgroundColor: "#231D3D", paddingHorizontal: 9, paddingVertical: 7, alignItems: "center" },
  recipeCaloriesValueV2: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  recipeCaloriesLabelV2: { color: "#A995FF", fontSize: 9, fontWeight: "800", marginTop: 1 },
  recipeMacroRowV2: { flexDirection: "row", gap: 7, marginTop: 12 },
  recipeMacroPillV2: { backgroundColor: "#202838", borderRadius: 10, paddingHorizontal: 9, paddingVertical: 6 },
  recipeMacroTextV2: { color: "#B9C3D4", fontSize: 10, fontWeight: "800" },
  recipeTapHintV2: { color: "#7E8A9F", fontSize: 10, marginTop: 10 },
  recipeActionsV2: { flexDirection: "row", borderTopWidth: 1, borderTopColor: "#293348", padding: 8, gap: 7 },
  recipeSecondaryButtonV2: { flex: 1, backgroundColor: "#202838", borderRadius: 11, paddingVertical: 9, alignItems: "center" },
  recipeSecondaryButtonTextV2: { color: "#B8C2D3", fontSize: 11, fontWeight: "900" },
  recipeDeleteButtonV2: { flex: 1, backgroundColor: "#2A1D25", borderRadius: 11, paddingVertical: 9, alignItems: "center" },
  recipeLiveSummaryV2: { backgroundColor: "#161D2A", borderRadius: 18, borderWidth: 1, borderColor: "#2A3448", padding: 14, marginTop: 8, marginBottom: 18 },
  recipeLiveTitleV2: { color: "#A995FF", fontSize: 11, fontWeight: "900", textTransform: "uppercase", letterSpacing: 0.7, marginBottom: 12 },
  recipeLiveStatsV2: { flexDirection: "row", justifyContent: "space-between" },
  recipeLiveValueV2: { color: "#FFFFFF", fontSize: 14, fontWeight: "900", textAlign: "center" },
  recipeLiveLabelV2: { color: "#8390A5", fontSize: 9, fontWeight: "700", textAlign: "center", marginTop: 3 },
  recipeMain: {
    flex: 1,
    paddingRight: 10,
  },
  recipeName: { color: "#FFFFFF", fontSize: 15, fontWeight: "900",
  },
  recipeDetails: { color: "#8F9AAF", fontSize: 11, marginTop: 4,
  },
  recipeActions: {
    alignItems: "flex-end",
    gap: 4,
  },
  recipeEditButton: {
    paddingHorizontal: 8,
    paddingVertical: 6,
  },
  recipeEditText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
  },
  recipeDeleteButton: {
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  recipeDeleteText: {
    color: "#A23D32",
    fontSize: 13,
    fontWeight: "900",
  },
  recipeScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  recipeModalHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  recipeModalTitle: {
    color: theme.text,
    fontSize: 26,
    fontWeight: "900",
  },
  recipeModalClose: {
    color: theme.primary,
    fontSize: 16,
    fontWeight: "800",
  },
  recipeModalContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  recipeLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 8,
  },
  recipeInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 17,
    marginBottom: 14,
  },
  recipeSubTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: "900",
    marginTop: 8,
    marginBottom: 12,
  },
  recipeHelperText: {
    color: theme.textMuted,
    fontSize: 12,
    marginTop: -6,
    marginBottom: 10,
  },
  recipeIngredientRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  recipeSearchRow: {
    backgroundColor: theme.card,
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
  },
  selectedRecipeFood: {
    backgroundColor: theme.soft,
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
  },
  addIngredientButton: {
    backgroundColor: theme.primary,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  addIngredientButtonText: {
    color: theme.card,
    fontSize: 15,
    fontWeight: "900",
  },
  saveRecipeButton: {
    backgroundColor: theme.primaryDark,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
    marginTop: 18,
  },
  saveRecipeButtonText: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "900",
  },
  quickSection: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 14, marginBottom: 12,
  },
  quickSectionTitle: { color: "#F5F7FC", fontSize: 17, fontWeight: "900",
  },
  quickFoodRow: { flexDirection: "row", alignItems: "center", borderTopWidth: 1, borderTopColor: "#252E40", paddingVertical: 11,
  },
  quickFoodMain: {
    flex: 1,
    paddingRight: 10,
  },
  quickFoodName: { color: "#FFFFFF", fontSize: 14, fontWeight: "800",
  },
  quickFoodDetails: { color: "#8F9AAF", fontSize: 11, marginTop: 3,
  },
  foodMainPress: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  favoriteButton: { width: 38, height: 38, borderRadius: 12, backgroundColor: "#1A2130", alignItems: "center", justifyContent: "center",
  },
  favoriteButtonText: { color: "#FFD04A", fontSize: 20,
  },
  scanButton: { backgroundColor: "#7458F5", borderRadius: 18, paddingVertical: 16, alignItems: "center", marginTop: 5, shadowColor: "#7458F5", shadowOpacity: 0.35, shadowRadius: 12, elevation: 6,
  },
  scanButtonText: { color: "#FFFFFF", fontSize: 15, fontWeight: "900",
  },
  foodDatabaseStatus: { flexDirection: "row", alignItems: "center", gap: 8, paddingVertical: 10,
  },
  foodDatabaseStatusText: { color: "#8792A7", fontSize: 11, flex: 1,
  },
  foodBrand: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 2,
  },
  foodSource: {
    color: theme.textMuted,
    fontSize: 10,
    fontWeight: "700",
    marginTop: 3,
  },
  searchInput: { backgroundColor: "#111722", color: "#FFFFFF", borderWidth: 1, borderColor: "#273044", borderRadius: 17, paddingHorizontal: 15, paddingVertical: 14, marginTop: 12, fontSize: 14,
  },
  foodItem: {
    backgroundColor: "#111722",
    borderWidth: 1,
    borderColor: "#273044",
    borderRadius: 16,
    padding: 17,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  foodTextArea: {
    flex: 1,
    paddingRight: 12,
  },
  foodName: {
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 5,
  },
  foodProtein: {
    color: theme.textMuted,
    fontSize: 13,
  },
  foodCalories: {
    color: "#F2F5FA",
    fontSize: 15,
    fontWeight: "800",
  },
  foodRight: {
    alignItems: "flex-end",
  },
  addText: {
    color: "#3E714F",
    fontSize: 13,
    fontWeight: "800",
    marginTop: 5,
  },
  noResults: {
    color: "#757D76",
    textAlign: "center",
    paddingVertical: 30,
    fontSize: 15,
  },
  scannerContainer: {
    flex: 1,
    backgroundColor: "#07150E",
  },
  scannerHeader: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scannerTitle: {
    color: theme.card,
    fontSize: 22,
    fontWeight: "900",
  },
  closeButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: theme.card,
    borderRadius: 10,
  },
  closeButtonText: {
    color: theme.text,
    fontWeight: "800",
  },
  camera: {
    flex: 1,
    marginHorizontal: 16,
    borderRadius: 20,
    overflow: "hidden",
  },
  scannerInstructions: {
    minHeight: 120,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 25,
  },
  instructionText: {
    color: theme.card,
    textAlign: "center",
    fontSize: 16,
    marginTop: 12,
  },
  productResult: {
    flex: 1,
    justifyContent: "center",
    paddingHorizontal: 25,
  },
  resultLabel: {
    color: "#87B796",
    fontWeight: "900",
    letterSpacing: 2,
    marginBottom: 14,
  },
  resultName: {
    color: theme.card,
    fontSize: 30,
    fontWeight: "900",
    marginBottom: 25,
  },
  amountLabel: {
    color: theme.card,
    fontSize: 16,
    fontWeight: "800",
    marginBottom: 10,
  },
  amountInput: {
    backgroundColor: theme.card,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 18,
    marginBottom: 12,
  },
  quickAmountRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 18,
  },
  quickAmountButton: {
    flex: 1,
    backgroundColor: "#163A27",
    borderRadius: 10,
    paddingVertical: 11,
    alignItems: "center",
  },
  quickAmountText: {
    color: theme.card,
    fontWeight: "800",
  },
  resultGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  resultValue: {
    width: "48%",
    backgroundColor: "#163A27",
    color: theme.card,
    paddingVertical: 18,
    paddingHorizontal: 10,
    borderRadius: 14,
    textAlign: "center",
    fontWeight: "900",
  },
  perHundredText: {
    color: "#AFBDB4",
    marginTop: 13,
    marginBottom: 30,
  },
  addScannedButton: {
    backgroundColor: theme.card,
    borderRadius: 15,
    paddingVertical: 17,
    alignItems: "center",
  },
  addScannedButtonText: {
    color: "#092A1B",
    fontSize: 16,
    fontWeight: "900",
  },
  scanAgainButton: {
    paddingVertical: 18,
    alignItems: "center",
  },
  scanAgainText: {
    color: theme.card,
    fontWeight: "800",
  },

  themeTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  currentThemeText: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: "800",
  },
  themeTopButton: {
    backgroundColor: theme.soft,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  themeTopButtonText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
  },
  themePickerCard: {
    backgroundColor: theme.card,
    borderRadius: 22,
    padding: 20,
    width: "90%",
    maxWidth: 420,
  },
  themeOption: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    padding: 14,
    marginBottom: 10,
  },
  themeOptionActive: {
    backgroundColor: theme.soft,
    borderColor: theme.primary,
  },
  themeColorDot: {
    width: 22,
    height: 22,
    borderRadius: 11,
    marginRight: 12,
  },
  themeOptionText: {
    flex: 1,
    color: theme.text,
    fontSize: 16,
    fontWeight: "900",
  },
  themeSelectedText: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
  },

  autoMacroButton: {
    backgroundColor: theme.soft,
    borderWidth: 1,
    borderColor: theme.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
  },
  autoMacroButtonText: {
    color: theme.primary,
    fontSize: 15,
    fontWeight: "900",
  },
  autoMacroDescription: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginBottom: 14,
  },

  macroModalScreen: {
    flex: 1,
    backgroundColor: theme.background,
  },
  macroKeyboardView: {
    flex: 1,
  },
  macroModalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
    backgroundColor: theme.background,
  },
  macroModalHeaderText: {
    flex: 1,
    paddingRight: 14,
  },
  macroModalTitle: {
    color: theme.text,
    fontSize: 28,
    fontWeight: "900",
    lineHeight: 34,
  },
  macroModalSubtitle: {
    color: theme.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 4,
  },
  macroModalCloseButton: {
    backgroundColor: theme.soft,
    borderRadius: 12,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  macroModalCloseText: {
    color: theme.primary,
    fontSize: 14,
    fontWeight: "900",
  },
  macroModalScroll: {
    flex: 1,
  },
  macroModalContent: {
    padding: 20,
    paddingBottom: 48,
  },
  macroInputCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 16,
    marginTop: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  macroGoalInput: {
    backgroundColor: theme.background,
    color: theme.text,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 20,
    fontWeight: "800",
    marginBottom: 16,
  },
  macroSuggestionCard: {
    backgroundColor: theme.soft,
    borderRadius: 14,
    padding: 13,
    marginTop: 10,
  },

  historyMacroGrid: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
    marginBottom: 12,
  },
  historyMacroCard: {
    flex: 1,
    backgroundColor: theme.soft,
    borderRadius: 14,
    padding: 11,
    minHeight: 92,
  },
  historyMacroLabel: {
    color: theme.textMuted,
    fontSize: 10,
    fontWeight: "800",
    marginBottom: 6,
  },
  historyMacroValue: {
    color: theme.text,
    fontSize: 17,
    fontWeight: "900",
  },
  historyMacroSubtext: {
    color: theme.textMuted,
    fontSize: 9,
    marginTop: 3,
  },
  weekComparisonCard: {
    backgroundColor: theme.background,
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: 14,
    padding: 13,
    marginBottom: 14,
  },
  weekComparisonTitle: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 4,
  },
  weekComparisonValue: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "900",
  },

  mealDistributionCard: {
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  mealDistributionTitle: {
    color: theme.text,
    fontSize: 18,
    fontWeight: "900",
  },
  mealDistributionSubtitle: {
    color: theme.textMuted,
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
    marginBottom: 14,
  },
  mealDistributionRow: {
    marginBottom: 14,
  },
  mealDistributionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  mealDistributionMeal: {
    color: theme.text,
    fontSize: 14,
    fontWeight: "900",
  },
  mealDistributionCalories: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
  },
  mealDistributionTrack: {
    height: 9,
    backgroundColor: theme.soft,
    borderRadius: 999,
    overflow: "hidden",
  },
  mealDistributionFill: {
    height: "100%",
    backgroundColor: theme.primary,
    borderRadius: 999,
  },
  mealDistributionMacros: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 5,
  },

  settingsCard: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 15, marginBottom: 12,
  },
  settingsCardTitle: { color: "#F7F9FD", fontSize: 16, fontWeight: "900", marginBottom: 6,
  },
  settingsRow: { flexDirection: "row", alignItems: "center", paddingVertical: 14, borderTopWidth: 1, borderTopColor: "#252E40",
  },
  settingsRowText: {
    flex: 1,
    paddingRight: 12,
  },
  settingsRowTitle: { color: "#FFFFFF", fontSize: 14, fontWeight: "800",
  },
  settingsRowDescription: { color: "#8F9AAF", fontSize: 11, marginTop: 4,
  },
  settingsRowArrow: { color: "#9B87FF", fontSize: 24,
  },
  settingsDangerRow: {
    paddingVertical: 14,
    borderTopWidth: 1,
    borderTopColor: theme.border,
  },
  settingsDangerTitle: {
    color: "#A23D32",
    fontSize: 15,
    fontWeight: "900",
    marginBottom: 3,
  },
  profileSummaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  profileSummaryItem: { width: "48%", backgroundColor: "#171E2B", borderRadius: 15, padding: 12, marginBottom: 8,
  },
  profileSummaryLabel: { color: "#8792A7", fontSize: 10, fontWeight: "800",
  },
  profileSummaryValue: { color: "#FFFFFF", fontSize: 14, fontWeight: "900", marginTop: 5,
  },
  settingsHint: { color: "#8792A7", fontSize: 11, lineHeight: 17, marginTop: 12,
  },


  personalWelcomeCard: {
    backgroundColor: theme.card,
    borderRadius: 24,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.border,
  },
  personalGreeting: {
    color: theme.text,
    fontSize: 24,
    fontWeight: "900",
    marginBottom: 4,
  },
  personalDate: {
    color: theme.textMuted,
    fontSize: 13,
    fontWeight: "700",
    marginBottom: 16,
  },
  personalStatsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  personalStatCard: {
    flex: 1,
    backgroundColor: theme.soft,
    borderRadius: 16,
    padding: 12,
  },
  personalStatIcon: {
    fontSize: 18,
    marginBottom: 5,
  },
  personalStatValue: {
    color: theme.text,
    fontSize: 20,
    fontWeight: "900",
  },
  personalStatLabel: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: "700",
    marginTop: 2,
  },
  personalWeightRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: theme.border,
    paddingTop: 12,
  },
  personalWeightRight: {
    alignItems: "flex-end",
  },
  personalWeightLabel: {
    color: theme.textMuted,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 3,
  },
  personalWeightValue: {
    color: theme.text,
    fontSize: 16,
    fontWeight: "900",
  },
  personalTargetText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 10,
  },

  dashboardHero: {
    backgroundColor: theme.soft,
    borderRadius: 26,
    padding: 16,
    marginBottom: 14,
    overflow: "hidden",
  },
  dashboardTopActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 8,
    marginBottom: 8,
  },
  dashboardSmallButton: {
    backgroundColor: theme.card,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: theme.border,
  },
  dashboardSmallButtonText: {
    color: theme.primary,
    fontSize: 12,
    fontWeight: "900",
  },
  calorieDashboard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 18,
    paddingVertical: 10,
  },
  calorieSideStat: {
    width: "22%",
    alignItems: "center",
  },
  calorieSideLabel: {
    color: theme.text,
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 4,
  },
  calorieSideValue: {
    color: theme.text,
    fontSize: 30,
    fontWeight: "400",
  },
  calorieRing: {
    width: 174,
    height: 174,
    alignItems: "center",
    justifyContent: "center",
  },
  calorieRingSvg: {
    position: "absolute",
    top: 0,
    left: 0,
  },
  calorieRingContent: {
    width: 146,
    height: 146,
    borderRadius: 73,
    backgroundColor: theme.background,
    alignItems: "center",
    justifyContent: "center",
  },
  calorieRingLabel: {
    color: theme.text,
    fontSize: 15,
    fontWeight: "700",
  },
  calorieRingValue: {
    color: theme.text,
    fontSize: 44,
    fontWeight: "500",
    lineHeight: 52,
  },
  calorieRingGoal: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  calorieOverText: {
    color: "#A23D32",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
    marginTop: 4,
  },
  dashboardMacroRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 20,
  },
  dashboardMacroCard: {
    flex: 1,
    minWidth: 0,
    backgroundColor: theme.card,
    borderRadius: 15,
    paddingHorizontal: 9,
    paddingVertical: 11,
    borderWidth: 1,
    borderColor: theme.border,
  },
  dashboardMacroLabel: {
    color: theme.text,
    fontSize: 10,
    lineHeight: 13,
    fontWeight: "900",
    marginBottom: 5,
  },
  dashboardMacroValue: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 8,
  },
  dashboardMacroTrack: {
    height: 7,
    borderRadius: 999,
    backgroundColor: theme.soft,
    overflow: "hidden",
  },
  dashboardMacroFill: {
    height: "100%",
    backgroundColor: theme.primary,
    borderRadius: 999,
  },
  dashboardSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  dashboardSectionTitle: {
    color: theme.textMuted,
    fontSize: 17,
    fontWeight: "900",
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  dashboardMealCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.card,
    borderRadius: 20,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: theme.border,
  },
  dashboardMealIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.soft,
    marginRight: 13,
  },
  dashboardMealEmoji: {
    fontSize: 27,
  },
  dashboardMealMain: {
    flex: 1,
  },
  dashboardMealTitle: {
    color: theme.text,
    fontSize: 20,
    fontWeight: "900",
  },
  dashboardMealRecommendation: {
    color: theme.textMuted,
    fontSize: 12,
    marginTop: 3,
  },
  dashboardMealTotal: {
    color: theme.primary,
    fontSize: 13,
    fontWeight: "900",
    marginTop: 7,
  },
  dashboardMealItems: {
    marginTop: 7,
    gap: 5,
  },
  dashboardMealItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 8,
  },
  dashboardMealItemName: {
    flex: 1,
    color: theme.textMuted,
    fontSize: 12,
  },
  dashboardMealItemCalories: {
    color: theme.text,
    fontSize: 12,
    fontWeight: "800",
  },
  dashboardMoreItems: {
    color: theme.primary,
    fontSize: 11,
    fontWeight: "900",
  },
  dashboardAddButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: theme.soft,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  dashboardAddButtonText: {
    color: theme.primary,
    fontSize: 29,
    fontWeight: "400",
    lineHeight: 32,
  },
  dashboardQuickGrid: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
    marginBottom: 18,
  },
  dashboardQuickCard: {
    flex: 1,
    backgroundColor: theme.card,
    borderRadius: 18,
    padding: 15,
    borderWidth: 1,
    borderColor: theme.border,
  },
  dashboardQuickLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
  },
  dashboardQuickValue: {
    color: theme.text,
    fontSize: 20,
    fontWeight: "900",
    marginTop: 5,
  },
  dashboardQuickDescription: {
    color: theme.textMuted,
    fontSize: 11,
    marginTop: 3,
  },

  calorieConsumedCard: {
    minWidth: 86,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: theme.card,
    borderRadius: 18,
    paddingHorizontal: 12,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: theme.border,
  },
  calorieConsumedLabel: {
    color: theme.textMuted,
    fontSize: 12,
    fontWeight: "800",
    marginBottom: 4,
  },
  calorieConsumedValue: {
    color: theme.text,
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 34,
  },
  calorieConsumedUnit: {
    color: theme.textMuted,
    fontSize: 10,
    fontWeight: "800",
    marginTop: 2,
  },

  scannerCameraArea: {
    flex: 1,
    position: "relative",
    backgroundColor: "#000000",
  },
  scannerDarkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.18)",
  },
  scannerFocusFrame: {
    position: "absolute",
    top: "25%",
    left: "9%",
    width: "82%",
    height: 180,
    overflow: "hidden",
  },
  scannerCorner: {
    position: "absolute",
    width: 34,
    height: 34,
    borderColor: "#35E67B",
  },
  scannerCornerTopLeft: {
    top: 0,
    left: 0,
    borderTopWidth: 5,
    borderLeftWidth: 5,
    borderTopLeftRadius: 12,
  },
  scannerCornerTopRight: {
    top: 0,
    right: 0,
    borderTopWidth: 5,
    borderRightWidth: 5,
    borderTopRightRadius: 12,
  },
  scannerCornerBottomLeft: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
    borderBottomLeftRadius: 12,
  },
  scannerCornerBottomRight: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 5,
    borderRightWidth: 5,
    borderBottomRightRadius: 12,
  },
  scannerMovingLine: {
    position: "absolute",
    left: 10,
    right: 10,
    top: 0,
    height: 3,
    borderRadius: 999,
    backgroundColor: "#35E67B",
    shadowColor: "#35E67B",
    shadowOpacity: 0.9,
    shadowRadius: 8,
    shadowOffset: {
      width: 0,
      height: 0,
    },
  },
  scannerCameraControls: {
    position: "absolute",
    top: 20,
    right: 18,
  },
  scannerTorchButton: {
    backgroundColor: "rgba(0, 0, 0, 0.55)",
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.35)",
  },
  scannerTorchButtonActive: {
    backgroundColor: "#35E67B",
    borderColor: "#35E67B",
  },
  scannerTorchButtonText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "900",
  },
  scannerInstructionTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    fontWeight: "900",
    textAlign: "center",
    marginBottom: 6,
  },

  mealDetailScreen: {
    flex: 1,
    backgroundColor: "#070B14",
  },
  mealDetailHeader: {
    minHeight: 72,
    marginHorizontal: 16,
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#263044",
    backgroundColor: "#111827",
  },
  mealDetailBackButton: {
    width: 46,
    height: 46,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  mealDetailBackText: {
    color: "#FFFFFF",
    fontSize: 38,
    fontWeight: "300",
    lineHeight: 40,
  },
  mealDetailHeaderTitle: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  mealDetailHeaderSpacer: { width: 46 },
  mealDetailContent: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 54,
  },
  mealDetailSummaryCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#111827",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: "#263044",
    marginBottom: 16,
    shadowColor: "#000000",
    shadowOpacity: 0.25,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 7,
  },
  mealDetailScoreCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#D64D86",
    marginRight: 16,
    shadowColor: "#D64D86",
    shadowOpacity: 0.35,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
  },
  mealDetailScoreEmoji: { color: "#FFFFFF", fontSize: 25, fontWeight: "900" },
  mealDetailSummaryText: { flex: 1, paddingRight: 10 },
  mealDetailCalories: { color: "#F7F8FC", fontSize: 36, fontWeight: "900" },
  mealDetailRating: { color: "#F05B98", fontSize: 15, fontWeight: "900", marginTop: 4 },
  mealInsightCard: {
    backgroundColor: "#111827",
    borderRadius: 20,
    padding: 18,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "#263044",
  },
  mealInsightTitle: { color: "#A78BFA", fontSize: 13, fontWeight: "900", letterSpacing: 1.1, textTransform: "uppercase", marginBottom: 7 },
  mealInsightText: { color: "#AEB8CC", fontSize: 14, lineHeight: 21 },
  mealDetailSectionTitle: { color: "#F7F8FC", fontSize: 22, fontWeight: "900", marginBottom: 12 },
  mealNutrientCard: {
    backgroundColor: "#111827",
    borderRadius: 22,
    paddingHorizontal: 18,
    marginBottom: 26,
    borderWidth: 1,
    borderColor: "#263044",
  },
  mealNutrientRow: { minHeight: 68, flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 10 },
  mealNutrientLabel: { color: "#D8DEEA", fontSize: 16, fontWeight: "800" },
  mealNutrientValue: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", textAlign: "right" },
  mealNutrientDivider: { height: 1, backgroundColor: "#263044" },
  mealDetailEmptyCard: { backgroundColor: "#111827", borderRadius: 22, padding: 24, marginBottom: 18, borderWidth: 1, borderColor: "#263044", alignItems: "center" },
  mealDetailEmptyText: { color: "#AEB8CC", fontSize: 14, lineHeight: 20, textAlign: "center", marginTop: 6 },
  mealFoodList: { backgroundColor: "#111827", borderRadius: 22, paddingHorizontal: 16, marginBottom: 18, borderWidth: 1, borderColor: "#263044", overflow: "hidden" },
  mealFoodRow: { minHeight: 74, flexDirection: "row", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#263044" },
  mealFoodText: { flex: 1, paddingRight: 12 },
  mealFoodName: { color: "#F7F8FC", fontSize: 16, fontWeight: "900" },
  mealFoodAmount: { color: "#8F9BB0", fontSize: 13, marginTop: 4 },
  mealFoodCalories: { color: "#F7F8FC", fontSize: 15, fontWeight: "900" },
  mealAdjustButton: { backgroundColor: "#6F4EF6", borderRadius: 18, paddingVertical: 18, alignItems: "center", marginTop: 5, shadowColor: "#6F4EF6", shadowOpacity: 0.38, shadowRadius: 12, shadowOffset: { width: 0, height: 5 }, elevation: 7 },
  mealAdjustButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },

  mealGoalBadge: { minWidth: 64, paddingHorizontal: 10, paddingVertical: 9, borderRadius: 15, backgroundColor: "#171E2C", borderWidth: 1, borderColor: "#2A354A", alignItems: "center" },
  mealGoalBadgeValue: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  mealGoalBadgeLabel: { color: "#8F9BB0", fontSize: 9, fontWeight: "800", marginTop: 2 },
  mealProgressBlockLast: { borderBottomWidth: 0 },
  mealTipIconCircle: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#2A2414", alignItems: "center", justifyContent: "center" },
  mealSectionHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  mealItemCount: { color: "#8F9BB0", fontSize: 12, fontWeight: "800", marginTop: 5 },
  mealDetailEmptyIcon: { color: "#9B87FF", fontSize: 30, fontWeight: "500" },
  mealDetailEmptyTitle: { color: "#F7F8FC", fontSize: 17, fontWeight: "900", marginTop: 8 },
  mealFoodRowLast: { borderBottomWidth: 0 },
  mealFoodIcon: { width: 42, height: 42, borderRadius: 14, alignItems: "center", justifyContent: "center", marginRight: 12 },
  mealFoodIconText: { fontSize: 15, fontWeight: "900" },
  mealFoodValueColumn: { flexDirection: "row", alignItems: "center", gap: 8 },
  mealFoodChevron: { color: "#7F8AA0", fontSize: 26, fontWeight: "300" },
  mealDetailFooterCard: { flexDirection: "row", alignItems: "center", gap: 12, backgroundColor: "#0E1521", borderRadius: 20, borderWidth: 1, borderColor: "#263044", padding: 16, marginTop: 16 },
  mealDetailFooterCheck: { width: 34, height: 34, borderRadius: 17, borderWidth: 2, borderColor: "#8B6CFF", alignItems: "center", justifyContent: "center" },
  mealDetailFooterCheckText: { color: "#8B6CFF", fontSize: 17, fontWeight: "900" },
  mealDetailFooterTitle: { color: "#F7F8FC", fontSize: 14, fontWeight: "900" },
  mealDetailFooterText: { color: "#8F9BB0", fontSize: 12, marginTop: 3 },
  premiumPage: { backgroundColor: "#070B14" },
  premiumDashboard: { marginHorizontal: -2, paddingBottom: 30 },
  premiumHeader: { flexDirection: "row", alignItems: "center", marginBottom: 18, paddingTop: 4 },
  premiumAvatar: { width: 54, height: 54, borderRadius: 27, backgroundColor: "#7458F5", alignItems: "center", justifyContent: "center", shadowColor: "#7458F5", shadowOpacity: 0.45, shadowRadius: 14, shadowOffset: { width: 0, height: 4 }, elevation: 8 },
  premiumAvatarText: { color: "#FFFFFF", fontSize: 25, fontWeight: "900" },
  premiumHeaderText: { flex: 1, marginLeft: 14 },
  premiumGreeting: { color: "#FFFFFF", fontSize: 23, lineHeight: 29, fontWeight: "900" },
  premiumDate: { color: "#B4BDCF", fontSize: 14, marginTop: 3 },
  premiumSync: { color: "#42DB91", fontSize: 11, fontWeight: "800", marginTop: 4 },
  premiumSyncError: { color: "#FF687A" },
  premiumProfileButton: { width: 44, height: 44, borderRadius: 16, backgroundColor: "#141B29", borderWidth: 1, borderColor: "#283247", alignItems: "center", justifyContent: "center" },
  premiumProfileIcon: { fontSize: 19 },
  premiumDateNavigator: { alignSelf: "flex-end", flexDirection: "row", alignItems: "center", gap: 15, backgroundColor: "#121824", borderRadius: 18, paddingHorizontal: 14, paddingVertical: 8, borderWidth: 1, borderColor: "#273044", marginBottom: 14 },
  premiumDateArrow: { color: "#DDE3F0", fontSize: 25, fontWeight: "700", lineHeight: 25 },
  premiumTodayText: { color: "#F7F9FD", fontSize: 13, fontWeight: "800" },
  premiumSummaryCard: { backgroundColor: "#111722", borderRadius: 30, borderWidth: 1, borderColor: "#2B354B", padding: 18, shadowColor: "#000000", shadowOpacity: 0.46, shadowRadius: 22, shadowOffset: { width: 0, height: 10 }, elevation: 12 },
  premiumCardTitle: { color: "#F7F9FD", fontSize: 19, fontWeight: "900", marginBottom: 8 },
  premiumSummaryMain: { flexDirection: "row", alignItems: "center" },
  premiumRingWrap: { width: 188, height: 188, alignItems: "center", justifyContent: "center", marginLeft: -8 },
  premiumRingCenter: { position: "absolute", alignItems: "center" },
  premiumRingLabel: { color: "#B9C2D3", fontSize: 12, fontWeight: "700" },
  premiumRingValue: { color: "#FFFFFF", fontSize: 42, lineHeight: 47, fontWeight: "900", marginTop: 2 },
  premiumRingGoal: { color: "#A8B2C4", fontSize: 12 },
  premiumCaloriesPanel: { flex: 1, paddingLeft: 8 },
  premiumCaloriesLabel: { color: "#AEB8CA", fontSize: 12, fontWeight: "800" },
  premiumCaloriesValue: { color: "#FFFFFF", fontSize: 31, fontWeight: "900", marginTop: 3 },
  premiumCaloriesUnit: { color: "#AEB8CA", fontSize: 13 },
  premiumOverallTrack: { height: 8, backgroundColor: "#263044", borderRadius: 6, overflow: "hidden", marginTop: 14 },
  premiumOverallFill: { height: "100%", backgroundColor: "#3DE5A1", borderRadius: 6 },
  premiumPercentText: { color: "#AEB8CA", fontSize: 11, marginTop: 7 },
  premiumMacroGrid: { flexDirection: "row", gap: 8, marginTop: 12, paddingTop: 4 },
  premiumMacroItem: { flex: 1, minHeight: 126, alignItems: "flex-start", paddingHorizontal: 11, paddingVertical: 12, borderRadius: 18, borderWidth: 1, borderColor: "#313A50" },
  premiumMacroIconBubble: { width: 31, height: 31, borderRadius: 11, alignItems: "center", justifyContent: "center", marginBottom: 8 },
  premiumMacroIcon: { fontSize: 17 },
  premiumMacroValue: { color: "#FFFFFF", fontSize: 18, fontWeight: "900", marginTop: 3 },
  premiumMacroLabel: { color: "#B7C0D2", fontSize: 10, fontWeight: "800" },
  premiumMacroTrack: { width: "100%", height: 5, backgroundColor: "#2A3245", borderRadius: 4, overflow: "hidden", marginTop: 9 },
  premiumMacroFill: { height: "100%", backgroundColor: "#765CF7", borderRadius: 4 },
  premiumMacroGoal: { color: "#8F99AC", fontSize: 9, marginTop: 5 },
  premiumQuickAdd: { flexDirection: "row", alignItems: "center", backgroundColor: "#6F55F7", borderRadius: 22, paddingHorizontal: 15, paddingVertical: 14, marginTop: 14, shadowColor: "#6F55F7", shadowOpacity: 0.38, shadowRadius: 16, shadowOffset: { width: 0, height: 7 }, elevation: 9 },
  premiumQuickAddIcon: { width: 43, height: 43, borderRadius: 15, backgroundColor: "rgba(255,255,255,0.16)", alignItems: "center", justifyContent: "center" },
  premiumQuickAddPlus: { color: "#FFFFFF", fontSize: 29, fontWeight: "400", lineHeight: 31 },
  premiumQuickAddTextWrap: { flex: 1, marginLeft: 12 },
  premiumQuickAddTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  premiumQuickAddSubtitle: { color: "#E5DFFF", fontSize: 10, marginTop: 3 },
  premiumQuickAddArrow: { color: "#FFFFFF", fontSize: 29, fontWeight: "300", marginLeft: 8 },
  premiumSectionRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 24, marginBottom: 10 },
  premiumSectionTitle: { color: "#F7F9FD", fontSize: 20, fontWeight: "900" },
  premiumCopyText: { color: "#9B87FF", fontSize: 13, fontWeight: "900" },
  premiumMealCard: { backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 13, marginBottom: 10, flexDirection: "row", alignItems: "center" },
  premiumMealIconBox: { width: 54, height: 54, borderRadius: 17, alignItems: "center", justifyContent: "center", shadowColor: "#000", shadowOpacity: 0.2, shadowRadius: 5, elevation: 3 },
  premiumMealIcon: { fontSize: 25 },
  premiumMealContent: { flex: 1, marginHorizontal: 12 },
  premiumMealTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start" },
  premiumMealTitle: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  premiumMealCount: { color: "#8F9AAF", fontSize: 11, marginTop: 3 },
  premiumMealCalories: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  premiumMealUnit: { color: "#9DA7B9", fontSize: 11, fontWeight: "600" },
  premiumMealTrack: { height: 5, backgroundColor: "#293247", borderRadius: 4, overflow: "hidden", marginTop: 10 },
  premiumMealFill: { height: "100%", borderRadius: 4 },
  premiumAddButton: { width: 43, height: 43, borderRadius: 15, backgroundColor: "#1A2130", borderWidth: 1, borderColor: "#333E54", alignItems: "center", justifyContent: "center" },
  premiumAddText: { color: "#FFFFFF", fontSize: 27, fontWeight: "300", marginTop: -2 },
  premiumInsightGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginTop: 12 },
  premiumInsightCard: { width: "48.5%", minHeight: 132, backgroundColor: "#111722", borderRadius: 22, borderWidth: 1, borderColor: "#273044", padding: 15, marginBottom: 10 },
  premiumInsightHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  premiumInsightLabel: { color: "#F5F7FC", fontSize: 14, fontWeight: "900" },
  premiumPositiveText: { color: "#42DB91", fontSize: 11, fontWeight: "800" },
  premiumInsightValue: { color: "#FFFFFF", fontSize: 29, fontWeight: "900", marginTop: 16 },
  premiumInsightUnit: { color: "#A2ADBF", fontSize: 13, fontWeight: "600" },
  premiumInsightDescription: { color: "#8F9AAF", fontSize: 11, marginTop: 7 },
  premiumMiniRing: { width: 66, height: 66, borderRadius: 33, borderWidth: 7, borderColor: "#42DB91", alignItems: "center", justifyContent: "center", marginTop: 10, alignSelf: "center" },
  premiumMiniRingValue: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  premiumStreakValue: { color: "#FFFFFF", fontSize: 28, fontWeight: "900", marginTop: 18 },
  premiumScoreValue: { color: "#9B87FF", fontSize: 32, fontWeight: "900", marginTop: 16 },
  premiumScoreUnit: { color: "#9BA6B8", fontSize: 13 },
  premiumBottomNav: { backgroundColor: "#0E1420", borderTopColor: "#273044", paddingTop: 8, paddingBottom: 10 },
  premiumNavButton: { minHeight: 54, borderRadius: 16 },
  premiumNavIcon: { color: "#7F8AA0", fontSize: 23, fontWeight: "700", lineHeight: 24 },
  premiumNavIconActive: { color: "#8F76FF" },
  premiumNavText: { color: "#7F8AA0", fontSize: 10, marginTop: 4 },
  premiumNavTextActive: { color: "#9B87FF" },


  premiumTitleRow: { flexDirection: "row", alignItems: "flex-start" },
  premiumCalendarBadge: { width: 44, height: 44, borderRadius: 15, backgroundColor: "#121824", borderWidth: 1, borderColor: "#293246", alignItems: "center", justifyContent: "center" },
  premiumCalendarIcon: { color: "#A78BFA", fontSize: 20, fontWeight: "900" },
  premiumHistoryDate: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", backgroundColor: "#111722", borderRadius: 18, borderWidth: 1, borderColor: "#293246", paddingHorizontal: 16, paddingVertical: 11, marginTop: 16 },
  premiumHistoryArrow: { color: "#9B87FF", fontSize: 27, fontWeight: "700", lineHeight: 28 },
  premiumHistoryDateText: { color: "#F7F9FD", fontSize: 14, fontWeight: "900" },
  mealDetailMenu: { width: 46, color: "#FFFFFF", fontSize: 18, fontWeight: "900", textAlign: "center" },
  mealDetailSectionEyebrow: { color: "#9B87FF", fontSize: 12, fontWeight: "900", letterSpacing: 1.3, marginBottom: 10, marginTop: 5 },
  mealProgressBlock: { paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: "#202A3C" },
  mealProgressTrack: { height: 6, backgroundColor: "#293247", borderRadius: 6, overflow: "hidden", marginTop: 10 },
  mealProgressFill: { height: "100%", borderRadius: 6 },
  mealTipCard: { flexDirection: "row", gap: 12, backgroundColor: "#111827", borderRadius: 20, borderWidth: 1, borderColor: "#263044", padding: 16, marginBottom: 22 },
  mealDetailActionRow: { gap: 10, marginTop: 4 },
  mealDetailActionButton: { marginBottom: 0 },
  mealCopyButton: { height: 52, borderRadius: 18, borderWidth: 1, borderColor: "#4A3F70", backgroundColor: "#201A33", alignItems: "center", justifyContent: "center", marginBottom: 14 },
  mealCopyButtonText: { color: "#B9ABFF", fontSize: 14, fontWeight: "900" },
  mealTipIcon: { fontSize: 19 },
  mealTipTitle: { color: "#F7F8FC", fontSize: 16, fontWeight: "900", marginBottom: 4 },
  mealTipText: { color: "#AEB8CC", fontSize: 13, lineHeight: 19 },
  premiumScreenHeader: { marginBottom: 18, },
  premiumScreenEyebrow: { color: "#8F76FF", fontSize: 11, fontWeight: "900", letterSpacing: 1.5, },
  premiumScreenTitle: { color: "#FFFFFF", fontSize: 30, fontWeight: "900", marginTop: 4, },
  premiumScreenSubtitle: { color: "#8F9AAF", fontSize: 13, lineHeight: 19, marginTop: 6, },

  historyHeroCard: {
    backgroundColor: "#151B29",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#2D354A",
    padding: 18,
    marginBottom: 14,
  },
  historyHeroTopRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 18 },
  historyHeroEyebrow: { color: "#8E79FF", fontSize: 10, fontWeight: "900", letterSpacing: 1.4, marginBottom: 5 },
  historyHeroTitle: { color: "#FFFFFF", fontSize: 24, fontWeight: "900" },
  historyHeroSubtitle: { color: "#97A3BA", fontSize: 12, marginTop: 4 },
  historyGoalRing: { width: 74, height: 74, borderRadius: 37, borderWidth: 7, borderColor: "#7458F5", alignItems: "center", justifyContent: "center", backgroundColor: "#101521" },
  historyGoalRingValue: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  historyGoalRingLabel: { color: "#8F9AB0", fontSize: 9, fontWeight: "700", marginTop: 1 },
  historyStatsRow: { flexDirection: "row", gap: 10 },
  historyStatCard: { flex: 1, backgroundColor: "#101521", borderRadius: 17, borderWidth: 1, borderColor: "#293248", padding: 14 },
  historyStatIcon: { fontSize: 17, marginBottom: 8 },
  historyStatValue: { color: "#FFFFFF", fontSize: 22, fontWeight: "900" },
  historyStatLabel: { color: "#9DA8BC", fontSize: 10, fontWeight: "700", marginTop: 3 },
  historyTrendCard: { backgroundColor: "#151B29", borderRadius: 24, borderWidth: 1, borderColor: "#30394F", padding: 17, marginBottom: 14, shadowColor: "#000", shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 7 }, elevation: 4 },
  historySectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  historySectionEyebrow: { color: "#8E79FF", fontSize: 9, fontWeight: "900", letterSpacing: 1.2, marginBottom: 4 },
  historySectionTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  historyGoalBadge: { backgroundColor: "#25203D", borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7 },
  historyGoalBadgeText: { color: "#B8A9FF", fontSize: 10, fontWeight: "900" },
  historyChart: { height: 158, flexDirection: "row", alignItems: "flex-end", gap: 6 },
  historyChartColumn: { flex: 1, height: 158, alignItems: "center", justifyContent: "flex-end" },
  historyChartValue: { color: "#AEB8CA", fontSize: 8, marginBottom: 4 },
  historyChartTrack: { width: "72%", height: 112, borderRadius: 8, backgroundColor: "#20283A", justifyContent: "flex-end", overflow: "hidden" },
  historyChartBar: { width: "100%", minHeight: 8, borderRadius: 8, backgroundColor: "#7458F5" },
  historyChartBarOnGoal: { backgroundColor: "#4DD5B2" },
  historyChartDate: { color: "#8995AA", fontSize: 8, marginTop: 6 },
  historyMacroOverviewCard: { backgroundColor: "#151B29", borderRadius: 24, borderWidth: 1, borderColor: "#30394F", padding: 17, marginBottom: 14, shadowColor: "#000", shadowOpacity: 0.16, shadowRadius: 12, shadowOffset: { width: 0, height: 7 }, elevation: 4 },
  historyMacroPremiumRow: { flexDirection: "row", gap: 8 },
  historyMacroPremiumCard: { flex: 1, backgroundColor: "#101521", borderRadius: 15, padding: 11, borderWidth: 1, borderColor: "#293248" },
  historyMacroDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 9 },
  historyMacroPremiumValue: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  historyMacroPremiumLabel: { color: "#9DA8BC", fontSize: 8, marginTop: 4 },
  historyMacroBar: { height: 9, borderRadius: 6, overflow: "hidden", flexDirection: "row", marginTop: 14, backgroundColor: "#222A3B" },
  historyMacroBarProtein: { backgroundColor: "#B26BFF" },
  historyMacroBarCarbs: { backgroundColor: "#FFB04A" },
  historyMacroBarFat: { backgroundColor: "#4DD5B2" },
  historyComparisonPremiumCard: { backgroundColor: "#151B29", borderRadius: 20, borderWidth: 1, borderColor: "#2D354A", padding: 15, marginBottom: 14, flexDirection: "row", alignItems: "center", gap: 12 },
  historyComparisonIconWrap: { width: 40, height: 40, borderRadius: 14, backgroundColor: "#25203D", alignItems: "center", justifyContent: "center" },
  historyComparisonIcon: { color: "#9B86FF", fontSize: 20, fontWeight: "900" },
  historyComparisonLabel: { color: "#909CB2", fontSize: 10, fontWeight: "800", marginBottom: 4 },
  historyComparisonValue: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" },

  // v5.4 – premium profil
  profileHeroCard: { backgroundColor: "#171D2B", borderRadius: 28, borderWidth: 1, borderColor: "#30394F", padding: 18, marginBottom: 22, shadowColor: "#000", shadowOpacity: 0.22, shadowRadius: 18, shadowOffset: { width: 0, height: 10 }, elevation: 7 },
  profileHeroTopRow: { flexDirection: "row", alignItems: "center" },
  profileAvatar: { width: 62, height: 62, borderRadius: 22, backgroundColor: "#7357F2", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#9A86FF" },
  profileAvatarText: { color: "#FFFFFF", fontSize: 25, fontWeight: "900" },
  profileHeroIdentity: { flex: 1, marginLeft: 13 },
  profileHeroEyebrow: { color: "#9B86FF", fontSize: 9, fontWeight: "900", letterSpacing: 1.3, marginBottom: 4 },
  profileHeroName: { color: "#FFFFFF", fontSize: 21, fontWeight: "900" },
  profileHeroEmail: { color: "#96A1B5", fontSize: 11, marginTop: 3 },
  profilePremiumBadge: { backgroundColor: "#28213F", borderRadius: 999, paddingHorizontal: 9, paddingVertical: 6, borderWidth: 1, borderColor: "#4A3F70" },
  profilePremiumBadgeText: { color: "#B9ABFF", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  profileStatsRow: { flexDirection: "row", alignItems: "center", marginTop: 18, paddingTop: 16, borderTopWidth: 1, borderTopColor: "#293146" },
  profileStatItem: { flex: 1, alignItems: "center" },
  profileStatValue: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" },
  profileStatLabel: { color: "#8995AA", fontSize: 9, marginTop: 4 },
  profileStatDivider: { width: 1, height: 28, backgroundColor: "#30384B" },
  profileSectionHeader: { marginBottom: 11, marginTop: 2 },
  profileSectionEyebrow: { color: "#8E79FF", fontSize: 9, fontWeight: "900", letterSpacing: 1.25, marginBottom: 4 },
  profileSectionTitle: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" },
  profileGoalGrid: { flexDirection: "row", gap: 10, marginBottom: 12 },
  profileGoalCard: { flex: 1, backgroundColor: "#151B29", borderRadius: 22, borderWidth: 1, borderColor: "#2D354A", padding: 15 },
  profileGoalIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", marginBottom: 14 },
  profileGoalIconPurple: { backgroundColor: "#2A2244" },
  profileGoalIconGreen: { backgroundColor: "#173B34" },
  profileGoalIconText: { color: "#FFFFFF", fontSize: 19, fontWeight: "900" },
  profileGoalLabel: { color: "#9CA7BA", fontSize: 10, fontWeight: "800", marginBottom: 4 },
  profileGoalValue: { color: "#FFFFFF", fontSize: 24, fontWeight: "900" },
  profileGoalUnit: { color: "#7F8BA1", fontSize: 9, marginTop: 3 },
  profileMacroCard: { backgroundColor: "#151B29", borderRadius: 24, borderWidth: 1, borderColor: "#30394F", padding: 16, marginBottom: 22, shadowColor: "#000", shadowOpacity: 0.14, shadowRadius: 11, shadowOffset: { width: 0, height: 6 }, elevation: 4 },
  profileCardHeaderRow: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  profileCardEyebrow: { color: "#8E79FF", fontSize: 8, fontWeight: "900", letterSpacing: 1.1, marginBottom: 3 },
  profileCardTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  profileCardArrow: { color: "#8F9AAF", fontSize: 26 },
  profileMacroRow: { flexDirection: "row", marginTop: 17, gap: 8 },
  profileMacroItem: { flex: 1, backgroundColor: "#101521", borderRadius: 15, borderWidth: 1, borderColor: "#293248", padding: 11 },
  profileMacroDot: { width: 8, height: 8, borderRadius: 4, marginBottom: 9 },
  profileMacroValue: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" },
  profileMacroLabel: { color: "#909CB1", fontSize: 9, marginTop: 3 },
  profileBodyCard: { backgroundColor: "#151B29", borderRadius: 24, borderWidth: 1, borderColor: "#2D354A", padding: 15, marginBottom: 22 },
  profileBodyGrid: { flexDirection: "row", flexWrap: "wrap", gap: 9 },
  profileBodyItem: { width: "48.5%", backgroundColor: "#101521", borderRadius: 16, borderWidth: 1, borderColor: "#293248", padding: 13 },
  profileBodyLabel: { color: "#8793A8", fontSize: 9, fontWeight: "800", marginBottom: 5 },
  profileBodyValue: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
  profileMenuCard: { backgroundColor: "#151B29", borderRadius: 24, borderWidth: 1, borderColor: "#2D354A", paddingHorizontal: 14, marginBottom: 14 },
  profileMenuRow: { minHeight: 72, flexDirection: "row", alignItems: "center" },
  profileMenuIcon: { width: 40, height: 40, borderRadius: 14, alignItems: "center", justifyContent: "center", marginRight: 12 },
  profileMenuIconPurple: { backgroundColor: "#2A2244" },
  profileMenuIconGreen: { backgroundColor: "#173B34" },
  profileMenuIconOrange: { backgroundColor: "#422E1D" },
  profileMenuIconText: { color: "#FFFFFF", fontSize: 17, fontWeight: "900" },
  profileMenuTextWrap: { flex: 1 },
  profileMenuTitle: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
  profileMenuSubtitle: { color: "#8995AA", fontSize: 10, marginTop: 4 },
  profileMenuArrow: { color: "#8A96AA", fontSize: 25 },
  profileMenuDivider: { height: 1, backgroundColor: "#293146", marginLeft: 52 },
  profileComingBadge: { backgroundColor: "#2A2341", borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 },
  profileComingBadgeText: { color: "#AF9FFF", fontSize: 8, fontWeight: "900", letterSpacing: 0.8 },
  profileLogoutButton: { height: 54, borderRadius: 18, backgroundColor: "#7357F2", alignItems: "center", justifyContent: "center", marginBottom: 10 },
  profileLogoutText: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" },
  profileDeleteButton: { height: 50, borderRadius: 18, borderWidth: 1, borderColor: "#57303A", backgroundColor: "#24161D", alignItems: "center", justifyContent: "center", marginBottom: 18 },
  profileDeleteText: { color: "#FF8295", fontSize: 13, fontWeight: "900" },

  // v6.3 – Historikk 2.0
  historyPeriodSelector: { flexDirection: "row", gap: 7, marginBottom: 13, padding: 5, borderRadius: 18, borderWidth: 1, borderColor: "#2D374D", backgroundColor: "#111725" },
  historyPeriodButton: { flex: 1, minHeight: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", paddingHorizontal: 4 },
  historyPeriodButtonActive: { backgroundColor: "#7357F2", shadowColor: "#7357F2", shadowOpacity: 0.28, shadowRadius: 9, shadowOffset: { width: 0, height: 4 }, elevation: 4 },
  historyPeriodButtonText: { color: "#8995AA", fontSize: 11, fontWeight: "900" },
  historyPeriodButtonTextActive: { color: "#FFFFFF" },

  // v6.2.1 – ryddig kopieringsmeny
  copyMenuButton: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, borderColor: "#343D55", backgroundColor: "#171E2D", alignItems: "center", justifyContent: "center" },
  copyMenuButtonPressed: { opacity: 0.68, transform: [{ scale: 0.96 }] },
  copyMenuButtonText: { color: "#9B86FF", fontSize: 18, fontWeight: "900", letterSpacing: 1.5, marginTop: -6 },
  copyMenuBackdrop: { flex: 1, backgroundColor: "rgba(2, 6, 14, 0.72)", justifyContent: "flex-end" },
  copyMenuSheet: { backgroundColor: "#111725", borderTopLeftRadius: 30, borderTopRightRadius: 30, borderWidth: 1, borderColor: "#30394F", paddingHorizontal: 20, paddingTop: 10, paddingBottom: Platform.OS === "ios" ? 30 : 20 },
  copyMenuHandle: { width: 44, height: 5, borderRadius: 999, backgroundColor: "#384258", alignSelf: "center", marginBottom: 20 },
  copyMenuEyebrow: { color: "#8E79FF", fontSize: 9, fontWeight: "900", letterSpacing: 1.4, marginBottom: 5 },
  copyMenuTitle: { color: "#FFFFFF", fontSize: 26, fontWeight: "900" },
  copyMenuSubtitle: { color: "#929EB3", fontSize: 12, marginTop: 5, marginBottom: 17 },
  copyMenuPrimaryRow: { minHeight: 72, borderRadius: 19, borderWidth: 1, borderColor: "#303A51", backgroundColor: "#171E2D", flexDirection: "row", alignItems: "center", paddingHorizontal: 14, marginBottom: 9 },
  copyMenuIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#2B2347", alignItems: "center", justifyContent: "center", marginRight: 12 },
  copyMenuIconText: { color: "#A995FF", fontSize: 20, fontWeight: "900" },
  copyMenuTextWrap: { flex: 1 },
  copyMenuRowTitle: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
  copyMenuRowSubtitle: { color: "#8F9AAF", fontSize: 10, marginTop: 4 },
  copyMenuArrow: { color: "#8895AA", fontSize: 25, marginLeft: 8 },
  copyMenuGroupTitle: { color: "#AEB8CA", fontSize: 11, fontWeight: "900", marginTop: 12, marginBottom: 8 },
  copyMenuMealRow: { minHeight: 55, borderBottomWidth: 1, borderBottomColor: "#263047", flexDirection: "row", alignItems: "center" },
  copyMenuMealEmoji: { width: 38, fontSize: 21 },
  copyMenuMealText: { flex: 1, color: "#F7F8FC", fontSize: 14, fontWeight: "800" },
  copyMenuCancel: { height: 52, borderRadius: 17, backgroundColor: "#7357F2", alignItems: "center", justifyContent: "center", marginTop: 17 },
  copyMenuCancelText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" },
  
  dashboardWeekCard: {
    backgroundColor: "#111722",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#2B354B",
    padding: 18,
    marginTop: 16,
  },
  dashboardWeekHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  dashboardWeekEyebrow: { color: "#8B6CFF", fontSize: 11, fontWeight: "800", letterSpacing: 1.4 },
  dashboardWeekTitle: { color: "#F6F8FC", fontSize: 20, fontWeight: "800", marginTop: 3 },
  dashboardWeekLink: { color: "#A99BFF", fontSize: 13, fontWeight: "700" },
  dashboardWeekStats: { flexDirection: "row", alignItems: "stretch", marginBottom: 18 },
  dashboardWeekStat: { flex: 1, alignItems: "center", paddingHorizontal: 4 },
  dashboardWeekStatValue: { color: "#FFFFFF", fontSize: 20, fontWeight: "900" },
  dashboardWeekStatUnit: { color: "#8994A8", fontSize: 10, fontWeight: "600", marginTop: 4, textAlign: "center" },
  dashboardWeekDivider: { width: 1, backgroundColor: "#293246", marginVertical: 2 },
  dashboardMiniChart: { flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", height: 102, paddingTop: 8 },
  dashboardMiniChartColumn: { flex: 1, alignItems: "center" },
  dashboardMiniBarTrack: { width: 18, height: 74, justifyContent: "flex-end", backgroundColor: "#1C2433", borderRadius: 9, overflow: "hidden" },
  dashboardMiniBar: { width: "100%", borderRadius: 9 },
  dashboardMiniChartLabel: { color: "#7F8A9D", fontSize: 10, fontWeight: "700", marginTop: 7, textTransform: "capitalize" },
  dashboardRecentCard: {
    backgroundColor: "#111722",
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "#2B354B",
    padding: 18,
    marginTop: 16,
  },
  dashboardRecentRow: { flexDirection: "row", alignItems: "center", paddingVertical: 10, borderTopWidth: 1, borderTopColor: "#20293A" },
  dashboardRecentIcon: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#24203D", marginRight: 11 },
  dashboardRecentIconText: { fontSize: 18 },
  dashboardRecentText: { flex: 1, minWidth: 0 },
  dashboardRecentName: { color: "#F4F6FA", fontSize: 14, fontWeight: "800" },
  dashboardRecentMeta: { color: "#7F8A9D", fontSize: 11, marginTop: 3 },
  dashboardRecentCalories: { color: "#C9C1FF", fontSize: 13, fontWeight: "800", marginLeft: 10 },
  // v6.6 – Favoritter 2.0
  favoriteV2Section: { backgroundColor: "#111722", borderRadius: 26, borderWidth: 1, borderColor: "#2B354B", padding: 16, marginBottom: 16 },
  favoriteV2Header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  favoriteV2CountBadge: { minWidth: 34, height: 34, borderRadius: 12, backgroundColor: "#2B2347", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#4A3E72" },
  favoriteV2CountText: { color: "#B8A8FF", fontSize: 13, fontWeight: "900" },
  favoriteV2SearchBox: { minHeight: 46, flexDirection: "row", alignItems: "center", borderRadius: 16, borderWidth: 1, borderColor: "#303A51", backgroundColor: "#171E2D", paddingHorizontal: 13, marginBottom: 11 },
  favoriteV2SearchIcon: { color: "#9D8BFF", fontSize: 20, marginRight: 9 },
  favoriteV2SearchInput: { flex: 1, color: "#FFFFFF", fontSize: 14, paddingVertical: 10 },
  favoriteV2Card: { minHeight: 74, flexDirection: "row", alignItems: "center", borderRadius: 18, borderWidth: 1, borderColor: "#29344A", backgroundColor: "#151C2A", paddingHorizontal: 10, marginBottom: 9 },
  favoriteV2Main: { flex: 1, flexDirection: "row", alignItems: "center", minWidth: 0, paddingVertical: 10 },
  favoriteV2Icon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#2D2742", alignItems: "center", justifyContent: "center", marginRight: 11 },
  favoriteV2IconText: { color: "#FFD25A", fontSize: 19, fontWeight: "900" },
  favoriteV2TextWrap: { flex: 1, minWidth: 0 },
  favoriteV2NameRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  favoriteV2Name: { flexShrink: 1, color: "#F7F8FC", fontSize: 14, fontWeight: "900" },
  favoriteV2PinnedBadge: { borderRadius: 999, paddingHorizontal: 6, paddingVertical: 3, backgroundColor: "#292244" },
  favoriteV2PinnedText: { color: "#B8A8FF", fontSize: 7, fontWeight: "900", letterSpacing: 0.7 },
  favoriteV2Meta: { color: "#8F9BB0", fontSize: 10, marginTop: 5 },
  favoriteV2PinButton: { width: 36, height: 36, borderRadius: 12, alignItems: "center", justifyContent: "center", backgroundColor: "#20283A", marginLeft: 7 },
  favoriteV2PinText: { color: "#A99AFF", fontSize: 18, fontWeight: "900" },
  favoriteV2AddButton: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: "#7357F2", marginLeft: 7 },
  favoriteV2AddText: { color: "#FFFFFF", fontSize: 24, fontWeight: "700", marginTop: -2 },
  favoriteV2EmptyCard: { alignItems: "center", justifyContent: "center", minHeight: 150, borderRadius: 20, borderWidth: 1, borderColor: "#29344A", backgroundColor: "#151C2A", padding: 18 },
  favoriteV2EmptyIcon: { color: "#8E79FF", fontSize: 34, marginBottom: 8 },
  favoriteV2EmptyTitle: { color: "#FFFFFF", fontSize: 16, fontWeight: "900", marginBottom: 5 },
  favoriteV2EmptyText: { color: "#8F9BB0", fontSize: 11, textAlign: "center", lineHeight: 17, paddingVertical: 8 },

  // v6.7 – Quality & UX
  uxToast: {
    position: "absolute",
    left: 18,
    right: 18,
    bottom: Platform.OS === "ios" ? 102 : 88,
    minHeight: 56,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#3B4760",
    backgroundColor: "#182131",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 14,
    paddingVertical: 10,
    shadowColor: "#000000",
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 9,
    zIndex: 50,
  },
  uxToastIcon: {
    width: 32,
    height: 32,
    borderRadius: 11,
    backgroundColor: "#27493D",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 11,
  },
  uxToastIconText: { color: "#76E6B3", fontSize: 17, fontWeight: "900" },
  uxToastText: { flex: 1, color: "#F7F9FC", fontSize: 13, fontWeight: "800", lineHeight: 18 },

  // v7.1 – Avansert statistikk
  advancedCalendarCard: { backgroundColor: "#111722", borderRadius: 26, borderWidth: 1, borderColor: "#2B354B", padding: 18, marginTop: 16 },
  advancedCalendarSummary: { minWidth: 58, height: 50, borderRadius: 16, backgroundColor: "#202A3D", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#34415B" },
  advancedCalendarSummaryValue: { color: "#77E3B3", fontSize: 17, fontWeight: "900" },
  advancedCalendarSummaryLabel: { color: "#8E9AAF", fontSize: 9, fontWeight: "700", marginTop: 1 },
  advancedCalendarWeekRow: { flexDirection: "row", marginTop: 14, marginBottom: 7 },
  advancedCalendarWeekday: { width: "14.2857%", textAlign: "center", color: "#758196", fontSize: 10, fontWeight: "800" },
  advancedCalendarGrid: { flexDirection: "row", flexWrap: "wrap" },
  advancedCalendarCell: { width: "14.2857%", aspectRatio: 1, alignItems: "center", justifyContent: "center" },
  advancedCalendarDay: { width: 33, height: 33, borderRadius: 12, backgroundColor: "#1B2332", alignItems: "center", justifyContent: "center" },
  advancedCalendarDayGoal: { backgroundColor: "#245442", borderWidth: 1, borderColor: "#4DC89A" },
  advancedCalendarDayUnder: { backgroundColor: "#3A3150", borderWidth: 1, borderColor: "#7E68A8" },
  advancedCalendarDayOver: { backgroundColor: "#56343B", borderWidth: 1, borderColor: "#CE6A78" },
  advancedCalendarDaySelected: { borderWidth: 2, borderColor: "#FFFFFF" },
  advancedCalendarDayText: { color: "#F5F7FB", fontSize: 11, fontWeight: "800" },
  advancedCalendarLegend: { flexDirection: "row", flexWrap: "wrap", alignItems: "center", marginTop: 12, gap: 10 },
  advancedCalendarLegendText: { color: "#8692A6", fontSize: 9, fontWeight: "700" },
  advancedCalendarAverage: { marginLeft: "auto", color: "#B7A9FF", fontSize: 10, fontWeight: "800" },
  advancedMacroTrendCard: { backgroundColor: "#111722", borderRadius: 26, borderWidth: 1, borderColor: "#2B354B", padding: 18, marginTop: 16, marginBottom: 8 },
  advancedMacroLegend: { flexDirection: "row", gap: 14, marginTop: 12, marginBottom: 12 },
  advancedMacroLegendProtein: { color: "#B26BFF", fontSize: 10, fontWeight: "800" },
  advancedMacroLegendCarbs: { color: "#FFB04A", fontSize: 10, fontWeight: "800" },
  advancedMacroLegendFat: { color: "#4DD5B2", fontSize: 10, fontWeight: "800" },
  advancedMacroChart: { height: 126, flexDirection: "row", alignItems: "flex-end", justifyContent: "space-between", paddingTop: 8 },
  advancedMacroColumn: { flex: 1, alignItems: "center" },
  advancedMacroBars: { height: 94, flexDirection: "row", alignItems: "flex-end", gap: 2 },
  advancedMacroBarProtein: { width: 5, minHeight: 4, backgroundColor: "#B26BFF", borderRadius: 4 },
  advancedMacroBarCarbs: { width: 5, minHeight: 4, backgroundColor: "#FFB04A", borderRadius: 4 },
  advancedMacroBarFat: { width: 5, minHeight: 4, backgroundColor: "#4DD5B2", borderRadius: 4 },
  advancedMacroLabel: { color: "#758196", fontSize: 8, fontWeight: "700", marginTop: 7 },

});
};
